### ISSUE TITLE
pre-training weight

### ISSUE THREAD

**Issue by 464hee** [ilmaro8/HE_adversarial_CNN#1]
So far, I still can't seem to find a solution to cope with the variations in staining in different centers, now that I've seen this paper of yours, it seems like a good idea, what's the status of your research @ilmaro8

**Comment by ilmaro8** [comment]
Hello, 
this library can be combined

**Comment by ilmaro8** [comment]
Hello,
this library can combined with Data-Driven Color Augmentation method (https://github.com/ilmaro8/Data_Driven_Color_Augmentation) to have only acceptable (in terms of color variation) augmented samples during training.
